// permissionset 50620 "WarrantyNotifMgt."
// {
//     Caption = 'Warranty Notification Management';
//     Assignable = true;

//     Permissions = tabledata "Warranty Notification Setup" = RIMD,
//                   tabledata "Warranty Notification Log" = RIMD,
//                   table "Warranty Notification Setup" = X,
//                   table "Warranty Notification Log" = X,
//                   page "Warranty Notification Setup" = X,
//                   page "Warranty Notification Log" = X,
//                   codeunit "Warranty Notification Mgt." = X,
//                   codeunit "Warranty Email Management" = X,
//                   codeunit "Warranty Job Queue Scheduler" = X,
//                   codeunit "Warranty Job Queue Description" = X; 
// }